const formGroupFieldData = [
	{
		label: "Name",
		idname: "name",
		required: true,
		type: "text",
	},
	{
		label: "Date",
		idname: "data",
		required: true,
		type: "date",
	},
	{
		label: "Time",
		idname: "time",
		required: true,
		type: "time",
	},
	{
		label: "Speaker",
		idname: "speaker",
		required: true,
		type: "text",
	},
	{
		label: "Organiser",
		idname: "organiser",
		required: true,
		type: "text",
	},
	{
		label: "Image",
		idname: "image",
		required: true,
		type: "text",
	},
	{
		label: "Mode",
		idname: "mode",
		required: true,
		type: "text",
	},
	{
		label: "City",
		idname: "city",
		required: false,
		type: "text",
	},
	{
		label: "State",
		idname: "state",
		required: false,
		type: "text",
	},
	{
		label: "Country",
		idname: "country",
		required: false,
		type: "text",
	},
	{
		label: "Location",
		idname: "location",
		required: false,
		type: "text",
	},
	{
		label: "Tages",
		idname: "tages",
		required: false,
		type: "text",
	},
	{
		label: "Preference",
		idname: "preference",
		required: false,
		type: "text",
	},
	{
		label: "Description",
		idname: "description",
		required: false,
		type: "text",
	},
	{
		label: "Number of Seats",
		idname: "numofseats",
		required: false,
		type: "number",
	},
	// {
	// 	label: "Likes",
	// 	idname: "likes",
	// 	required: false,
	// 	type: "number",
	// },
	{
		label: "Number of Seatsleft",
		idname: "numofseatsleft",
		required: false,
		type: "number",
	},
	{
		label: "Cost",
		idname: "cost",
		required: false,
		type: "number",
	},
	{
		label: "Community Name",
		idname: "communityname",
		required: false,
		type: "text",
	},
];
export default formGroupFieldData;
